package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TBBearPer;

@Repository("bearPerMapper")
public interface TBBearPerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TBBearPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TBBearPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    TBBearPer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(TBBearPer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bear_per
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKey(TBBearPer record);
}