package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TBBill;

@Repository("billMapper")
public interface TBBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TBBill record);
}