package com.myorder.dao;

import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Repository;

import com.myorder.model.TBBill;

@Controller
@Repository("billMapper")
public interface TBBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    int insert(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    int insertSelective(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    TBBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    int updateByPrimaryKeySelective(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Thu Jul 21 19:58:03 CST 2016
     */
    int updateByPrimaryKey(TBBill record);
}