package com.myorder.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.myorder.model.PackBill;
import com.myorder.model.TBBill;

@Repository("billMapper")
public interface TBBillMapper {
	
	List<TBBill> selectBySome(PackBill pb);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    int insert(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    int insertSelective(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    TBBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    int updateByPrimaryKeySelective(TBBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bill
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    int updateByPrimaryKey(TBBill record);
}