package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TBPaytype;

@Repository("payTypeMapper")
public interface TBPaytypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paytype
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TBPaytype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_paytype
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TBPaytype record);
}