package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TBPersmission;

@Repository("persmissionMapper")
public interface TBPersmissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TBPersmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TBPersmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    TBPersmission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(TBPersmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_persmission
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKey(TBPersmission record);
}