package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TBRecurity;

@Repository("recurityMapper")
public interface TBRecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TBRecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TBRecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    TBRecurity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(TBRecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_security
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKey(TBRecurity record);
}