package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.tbRole;

@Repository("roleMapper")
public interface tbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(tbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(tbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    tbRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(tbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKey(tbRole record);
}