package com.myorder.dao;

import org.springframework.stereotype.Repository;

import com.myorder.model.TbUser;

@Repository("userMapper")
public interface TbUserMapper {
	/**
	 * 登入方法
	 * @param record
	 * @return
	 */
	TbUser  selectByLogin(TbUser record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insert(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int insertSelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    TbUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKeySelective(TbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    int updateByPrimaryKey(TbUser record);
}