package com.myorder.model;

public class TBBearPer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bear_per.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bear_per.roleId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bear_per.permissinId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer permissinid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bear_per.id
     *
     * @return the value of tb_bear_per.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bear_per.id
     *
     * @param id the value for tb_bear_per.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bear_per.roleId
     *
     * @return the value of tb_bear_per.roleId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bear_per.roleId
     *
     * @param roleid the value for tb_bear_per.roleId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bear_per.permissinId
     *
     * @return the value of tb_bear_per.permissinId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getPermissinid() {
        return permissinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bear_per.permissinId
     *
     * @param permissinid the value for tb_bear_per.permissinId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setPermissinid(Integer permissinid) {
        this.permissinid = permissinid;
    }
}