package com.myorder.model;

import java.util.Date;

public class TBBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.id
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.userId
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.userName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.createDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.payDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private String paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.goodsName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.payType
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.money
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.number
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.goodsTpye
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private Integer goodstpye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bill.imageUrl
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    private String imageurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.id
     *
     * @return the value of tb_bill.id
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.id
     *
     * @param id the value for tb_bill.id
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.userId
     *
     * @return the value of tb_bill.userId
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.userId
     *
     * @param userid the value for tb_bill.userId
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.userName
     *
     * @return the value of tb_bill.userName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.userName
     *
     * @param username the value for tb_bill.userName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.createDate
     *
     * @return the value of tb_bill.createDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.createDate
     *
     * @param createdate the value for tb_bill.createDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.payDate
     *
     * @return the value of tb_bill.payDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public String getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.payDate
     *
     * @param paydate the value for tb_bill.payDate
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setPaydate(String paydate) {
        this.paydate = paydate == null ? null : paydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.goodsName
     *
     * @return the value of tb_bill.goodsName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.goodsName
     *
     * @param goodsname the value for tb_bill.goodsName
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.payType
     *
     * @return the value of tb_bill.payType
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.payType
     *
     * @param paytype the value for tb_bill.payType
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.money
     *
     * @return the value of tb_bill.money
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.money
     *
     * @param money the value for tb_bill.money
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.number
     *
     * @return the value of tb_bill.number
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.number
     *
     * @param number the value for tb_bill.number
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.goodsTpye
     *
     * @return the value of tb_bill.goodsTpye
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public Integer getGoodstpye() {
        return goodstpye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.goodsTpye
     *
     * @param goodstpye the value for tb_bill.goodsTpye
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setGoodstpye(Integer goodstpye) {
        this.goodstpye = goodstpye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bill.imageUrl
     *
     * @return the value of tb_bill.imageUrl
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bill.imageUrl
     *
     * @param imageurl the value for tb_bill.imageUrl
     *
     * @mbggenerated Sat Jul 23 17:00:56 CST 2016
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }
}