package com.myorder.model;

public class TBPaytype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paytype.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paytype.typeName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_paytype.typeCode
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private String typecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paytype.id
     *
     * @return the value of tb_paytype.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paytype.id
     *
     * @param id the value for tb_paytype.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paytype.typeName
     *
     * @return the value of tb_paytype.typeName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paytype.typeName
     *
     * @param typename the value for tb_paytype.typeName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_paytype.typeCode
     *
     * @return the value of tb_paytype.typeCode
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_paytype.typeCode
     *
     * @param typecode the value for tb_paytype.typeCode
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }
}