package com.myorder.model;

public class TBRecurity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_security.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_security.userId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_security.question
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_security.answer
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_security.id
     *
     * @return the value of tb_security.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_security.id
     *
     * @param id the value for tb_security.id
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_security.userId
     *
     * @return the value of tb_security.userId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_security.userId
     *
     * @param userid the value for tb_security.userId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_security.question
     *
     * @return the value of tb_security.question
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_security.question
     *
     * @param question the value for tb_security.question
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_security.answer
     *
     * @return the value of tb_security.answer
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_security.answer
     *
     * @param answer the value for tb_security.answer
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}