package com.myorder.model;

public class TbUser {

    private Integer id;


    private String username;


    private String loginname;


    private String password;


    private String address;


    private Integer sex;


    private Integer roleid;


    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.userName
     *
     * @return the value of tb_user.userName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.userName
     *
     * @param username the value for tb_user.userName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.loginName
     *
     * @return the value of tb_user.loginName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.loginName
     *
     * @param loginname the value for tb_user.loginName
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.passWord
     *
     * @return the value of tb_user.passWord
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.passWord
     *
     * @param password the value for tb_user.passWord
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.address
     *
     * @return the value of tb_user.address
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.address
     *
     * @param address the value for tb_user.address
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.roleId
     *
     * @return the value of tb_user.roleId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.roleId
     *
     * @param roleid the value for tb_user.roleId
     *
     * @mbggenerated Tue Jul 19 19:17:13 CST 2016
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}